//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMS_Vis.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSMS_Vis.Resources.ReportRes", typeof(ReportRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail ISO High/Low-Limit.
        /// </summary>
        public static string BIN1_TITLE {
            get {
                return ResourceManager.GetString("BIN1_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI 3 long side.
        /// </summary>
        public static string BIN10_TITLE {
            get {
                return ResourceManager.GetString("BIN10_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI 4 bottom side.
        /// </summary>
        public static string BIN11_TITLE {
            get {
                return ResourceManager.GetString("BIN11_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI 5 top side.
        /// </summary>
        public static string BIN12_TITLE {
            get {
                return ResourceManager.GetString("BIN12_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail L High/Low-Limit.
        /// </summary>
        public static string BIN2_TITLE {
            get {
                return ResourceManager.GetString("BIN2_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Z High/Low-Limit.
        /// </summary>
        public static string BIN3_TITLE {
            get {
                return ResourceManager.GetString("BIN3_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail C High/Low-Limit.
        /// </summary>
        public static string BIN4_TITLE {
            get {
                return ResourceManager.GetString("BIN4_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail R1 High/Low-Limit.
        /// </summary>
        public static string BIN5_TITLE {
            get {
                return ResourceManager.GetString("BIN5_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail R2 High/Low-Limit.
        /// </summary>
        public static string BIN6_TITLE {
            get {
                return ResourceManager.GetString("BIN6_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail System.
        /// </summary>
        public static string BIN7_TITLE {
            get {
                return ResourceManager.GetString("BIN7_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI 2 front side.
        /// </summary>
        public static string BIN9_TITLE {
            get {
                return ResourceManager.GetString("BIN9_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL Total.
        /// </summary>
        public static string EL_TOTAL {
            get {
                return ResourceManager.GetString("EL_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string ENDDATE {
            get {
                return ResourceManager.GetString("ENDDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in detail.
        /// </summary>
        public static string ERRORINDETAIL {
            get {
                return ResourceManager.GetString("ERRORINDETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please see the table for the increased error rate!.
        /// </summary>
        public static string ERRORRATEWARNING {
            get {
                return ResourceManager.GetString("ERRORRATEWARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error summary.
        /// </summary>
        public static string ERRORSUMMARY {
            get {
                return ResourceManager.GetString("ERRORSUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string FROM_LC {
            get {
                return ResourceManager.GetString("FROM_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to high.
        /// </summary>
        public static string HIGH_LC {
            get {
                return ResourceManager.GetString("HIGH_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        public static string HINT {
            get {
                return ResourceManager.GetString("HINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impedance.
        /// </summary>
        public static string IMPEDANCE {
            get {
                return ResourceManager.GetString("IMPEDANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inductance.
        /// </summary>
        public static string INDUCTANCE {
            get {
                return ResourceManager.GetString("INDUCTANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line:.
        /// </summary>
        public static string LINEID {
            get {
                return ResourceManager.GetString("LINEID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOT Number:.
        /// </summary>
        public static string LOTNUMBER {
            get {
                return ResourceManager.GetString("LOTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low.
        /// </summary>
        public static string LOW_LC {
            get {
                return ResourceManager.GetString("LOW_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower limit.
        /// </summary>
        public static string LOWERLIMIT {
            get {
                return ResourceManager.GetString("LOWERLIMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total passed.
        /// </summary>
        public static string MACHINECNT_GOOD {
            get {
                return ResourceManager.GetString("MACHINECNT_GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good bucket.
        /// </summary>
        public static string MACHINECNT_GOODBIN {
            get {
                return ResourceManager.GetString("MACHINECNT_GOODBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge bucket.
        /// </summary>
        public static string MACHINECNT_LASTBIN {
            get {
                return ResourceManager.GetString("MACHINECNT_LASTBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string MACHINECNT_TOTAL {
            get {
                return ResourceManager.GetString("MACHINECNT_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bin counters.
        /// </summary>
        public static string MACHINECOUNTERS {
            get {
                return ResourceManager.GetString("MACHINECOUNTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Number.:.
        /// </summary>
        public static string MACHINENUMBER {
            get {
                return ResourceManager.GetString("MACHINENUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string MAXIMAL {
            get {
                return ResourceManager.GetString("MAXIMAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement.
        /// </summary>
        public static string MEASUREMENT {
            get {
                return ResourceManager.GetString("MEASUREMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement values.
        /// </summary>
        public static string MEASUREMENTVALUES {
            get {
                return ResourceManager.GetString("MEASUREMENTVALUES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        public static string MINIMUM {
            get {
                return ResourceManager.GetString("MINIMUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrowing.
        /// </summary>
        public static string NARROWING {
            get {
                return ResourceManager.GetString("NARROWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string NARROWING_ENDPROD {
            get {
                return ResourceManager.GetString("NARROWING_ENDPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma -.
        /// </summary>
        public static string NARROWING_LL_SIGMA {
            get {
                return ResourceManager.GetString("NARROWING_LL_SIGMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string NARROWING_MODE {
            get {
                return ResourceManager.GetString("NARROWING_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not narrowed.
        /// </summary>
        public static string NARROWING_MODE_NOPAT {
            get {
                return ResourceManager.GetString("NARROWING_MODE_NOPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std. deviation.
        /// </summary>
        public static string NARROWING_MODE_STDEV {
            get {
                return ResourceManager.GetString("NARROWING_MODE_STDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string NARROWING_MODE_UNKNOWN {
            get {
                return ResourceManager.GetString("NARROWING_MODE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to end.
        /// </summary>
        public static string NARROWING_PART_TO_END {
            get {
                return ResourceManager.GetString("NARROWING_PART_TO_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Samples.
        /// </summary>
        public static string NARROWING_SAMPLECNT {
            get {
                return ResourceManager.GetString("NARROWING_SAMPLECNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrowing sections.
        /// </summary>
        public static string NARROWING_SECTIONS {
            get {
                return ResourceManager.GetString("NARROWING_SECTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Product.
        /// </summary>
        public static string NARROWING_STARTPROD {
            get {
                return ResourceManager.GetString("NARROWING_STARTPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma +.
        /// </summary>
        public static string NARROWING_UL_SIGMA {
            get {
                return ResourceManager.GetString("NARROWING_UL_SIGMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrowing method:.
        /// </summary>
        public static string NARROWINGMETHOD {
            get {
                return ResourceManager.GetString("NARROWINGMETHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;mode&gt;; lower limit: &lt;LL&gt;σ; upper limit: &lt;UL&gt;σ.
        /// </summary>
        public static string NARROWINGMETHODDATA {
            get {
                return ResourceManager.GetString("NARROWINGMETHODDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal.
        /// </summary>
        public static string NOMINALVAL {
            get {
                return ResourceManager.GetString("NOMINALVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string PAGE {
            get {
                return ResourceManager.GetString("PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string PAGE_OF {
            get {
                return ResourceManager.GetString("PAGE_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page x of 6.
        /// </summary>
        public static string PAGESAMPLE {
            get {
                return ResourceManager.GetString("PAGESAMPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part Number:.
        /// </summary>
        public static string PARTNUMBER {
            get {
                return ResourceManager.GetString("PARTNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcs..
        /// </summary>
        public static string PIECESSHORT {
            get {
                return ResourceManager.GetString("PIECESSHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability.
        /// </summary>
        public static string PROBABILITY {
            get {
                return ResourceManager.GetString("PROBABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AOI Failed total.
        /// </summary>
        public static string QUAL_AOI_FAILED_TOTAL {
            get {
                return ResourceManager.GetString("QUAL_AOI_FAILED_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL Failed.
        /// </summary>
        public static string QUAL_EL_FAILED {
            get {
                return ResourceManager.GetString("QUAL_EL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL Passed.
        /// </summary>
        public static string QUAL_EL_PASSED {
            get {
                return ResourceManager.GetString("QUAL_EL_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EL System Failed.
        /// </summary>
        public static string QUAL_EL_SYSTEM_FAILED {
            get {
                return ResourceManager.GetString("QUAL_EL_SYSTEM_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string QUAL_FAILED {
            get {
                return ResourceManager.GetString("QUAL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string QUAL_PASSED {
            get {
                return ResourceManager.GetString("QUAL_PASSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QUANTITY {
            get {
                return ResourceManager.GetString("QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string REPORTDATA {
            get {
                return ResourceManager.GetString("REPORTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete LOT.
        /// </summary>
        public static string REPORTDATA_COMPLETE_LOT {
            get {
                return ResourceManager.GetString("REPORTDATA_COMPLETE_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partial LOT.
        /// </summary>
        public static string REPORTDATA_PARTIAL_LOT {
            get {
                return ResourceManager.GetString("REPORTDATA_PARTIAL_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Report.
        /// </summary>
        public static string REPORTSUBTITLE {
            get {
                return ResourceManager.GetString("REPORTSUBTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Report ACT1210.
        /// </summary>
        public static string REPORTTITLE {
            get {
                return ResourceManager.GetString("REPORTTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance R1.
        /// </summary>
        public static string RESISTANCE_R1 {
            get {
                return ResourceManager.GetString("RESISTANCE_R1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resistance R2.
        /// </summary>
        public static string RESISTANCE_R2 {
            get {
                return ResourceManager.GetString("RESISTANCE_R2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std.Dev..
        /// </summary>
        public static string STANDARDDEVIATION {
            get {
                return ResourceManager.GetString("STANDARDDEVIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string STARTDATE {
            get {
                return ResourceManager.GetString("STARTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State:.
        /// </summary>
        public static string STATE {
            get {
                return ResourceManager.GetString("STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string TO_LC {
            get {
                return ResourceManager.GetString("TO_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UNIT {
            get {
                return ResourceManager.GetString("UNIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper limit.
        /// </summary>
        public static string UPPERLIMIT {
            get {
                return ResourceManager.GetString("UPPERLIMIT", resourceCulture);
            }
        }
    }
}
