//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMS_Vis.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSMS_Vis.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string ADVANCED {
            get {
                return ResourceManager.GetString("ADVANCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BTN_CANCEL {
            get {
                return ResourceManager.GetString("BTN_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BTN_CLOSE {
            get {
                return ResourceManager.GetString("BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Report ....
        /// </summary>
        public static string BTN_PRINT {
            get {
                return ResourceManager.GetString("BTN_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Label.
        /// </summary>
        public static string BTN_PRINT_LABEL {
            get {
                return ResourceManager.GetString("BTN_PRINT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report ....
        /// </summary>
        public static string BTN_PRINT_REPORT {
            get {
                return ResourceManager.GetString("BTN_PRINT_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Print Label ....
        /// </summary>
        public static string BTN_REPRINT_LABEL {
            get {
                return ResourceManager.GetString("BTN_REPRINT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Print Label.
        /// </summary>
        public static string BTN_REPRINT_LABEL_WND {
            get {
                return ResourceManager.GetString("BTN_REPRINT_LABEL_WND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string BTN_RESET {
            get {
                return ResourceManager.GetString("BTN_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Zoom.
        /// </summary>
        public static string BTN_RESETZOOM {
            get {
                return ResourceManager.GetString("BTN_RESETZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart PAT sampling.
        /// </summary>
        public static string BTN_RESTART_PAT {
            get {
                return ResourceManager.GetString("BTN_RESTART_PAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete LOT.
        /// </summary>
        public static string BTN_SELECT_COMPLETE_LOT {
            get {
                return ResourceManager.GetString("BTN_SELECT_COMPLETE_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected section.
        /// </summary>
        public static string BTN_SELECT_LOT_SECTION {
            get {
                return ResourceManager.GetString("BTN_SELECT_LOT_SECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string BTN_STARTPRINT {
            get {
                return ResourceManager.GetString("BTN_STARTPRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to Master.
        /// </summary>
        public static string CONNECTION_TO_MASTER {
            get {
                return ResourceManager.GetString("CONNECTION_TO_MASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        public static string COUNTER {
            get {
                return ResourceManager.GetString("COUNTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string COUNTER_FAIL {
            get {
                return ResourceManager.GetString("COUNTER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string COUNTER_HIGH {
            get {
                return ResourceManager.GetString("COUNTER_HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string COUNTER_LOW {
            get {
                return ResourceManager.GetString("COUNTER_LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string COUNTER_NAME {
            get {
                return ResourceManager.GetString("COUNTER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string COUNTER_PASS {
            get {
                return ResourceManager.GetString("COUNTER_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string COUNTER_TOTAL {
            get {
                return ResourceManager.GetString("COUNTER_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string DATABASE {
            get {
                return ResourceManager.GetString("DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital I/O.
        /// </summary>
        public static string DIGITAL_IO {
            get {
                return ResourceManager.GetString("DIGITAL_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string END_DATE {
            get {
                return ResourceManager.GetString("END_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string GOOD {
            get {
                return ResourceManager.GetString("GOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        public static string HUNGARIAN {
            get {
                return ResourceManager.GetString("HUNGARIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label counter.
        /// </summary>
        public static string LABEL_CNT {
            get {
                return ResourceManager.GetString("LABEL_CNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string LINE {
            get {
                return ResourceManager.GetString("LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string LOT {
            get {
                return ResourceManager.GetString("LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot information.
        /// </summary>
        public static string LOT_INFO {
            get {
                return ResourceManager.GetString("LOT_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot number.
        /// </summary>
        public static string LOT_NUMBER {
            get {
                return ResourceManager.GetString("LOT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        public static string MACHINE {
            get {
                return ResourceManager.GetString("MACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Signals.
        /// </summary>
        public static string MACHINE_SIGNALS {
            get {
                return ResourceManager.GetString("MACHINE_SIGNALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Devices.
        /// </summary>
        public static string MEASUREMENT_DEVICES {
            get {
                return ResourceManager.GetString("MEASUREMENT_DEVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string MENU_ITEM_CHARTS {
            get {
                return ResourceManager.GetString("MENU_ITEM_CHARTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string MENU_ITEM_EXIT {
            get {
                return ResourceManager.GetString("MENU_ITEM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MENU_ITEM_FILE {
            get {
                return ResourceManager.GetString("MENU_ITEM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PAT narrowed histograms.
        /// </summary>
        public static string MENU_ITEM_SHOWPATHISTO {
            get {
                return ResourceManager.GetString("MENU_ITEM_SHOWPATHISTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really restart the PAT smapling process?.
        /// </summary>
        public static string MSG_PAT_RESTART {
            get {
                return ResourceManager.GetString("MSG_PAT_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To switch the language, the program must be restarted. Restart now?.
        /// </summary>
        public static string MSG_SWITCH_LANGUAGE {
            get {
                return ResourceManager.GetString("MSG_SWITCH_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string NARROWING_ENDPROD {
            get {
                return ResourceManager.GetString("NARROWING_ENDPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma -.
        /// </summary>
        public static string NARROWING_LL_SIGMA {
            get {
                return ResourceManager.GetString("NARROWING_LL_SIGMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string NARROWING_MODE {
            get {
                return ResourceManager.GetString("NARROWING_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not narrowed.
        /// </summary>
        public static string NARROWING_MODE_NOPAT {
            get {
                return ResourceManager.GetString("NARROWING_MODE_NOPAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std. deviation.
        /// </summary>
        public static string NARROWING_MODE_STDEV {
            get {
                return ResourceManager.GetString("NARROWING_MODE_STDEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string NARROWING_MODE_UNKNOWN {
            get {
                return ResourceManager.GetString("NARROWING_MODE_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to end.
        /// </summary>
        public static string NARROWING_PART_TO_END {
            get {
                return ResourceManager.GetString("NARROWING_PART_TO_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. of Samples.
        /// </summary>
        public static string NARROWING_SAMPLECNT {
            get {
                return ResourceManager.GetString("NARROWING_SAMPLECNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select narrowing section.
        /// </summary>
        public static string NARROWING_SELECTOR_DLG {
            get {
                return ResourceManager.GetString("NARROWING_SELECTOR_DLG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Product.
        /// </summary>
        public static string NARROWING_STARTPROD {
            get {
                return ResourceManager.GetString("NARROWING_STARTPROD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigma +.
        /// </summary>
        public static string NARROWING_UL_SIGMA {
            get {
                return ResourceManager.GetString("NARROWING_UL_SIGMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string PRODUCT {
            get {
                return ResourceManager.GetString("PRODUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOT start with.
        /// </summary>
        public static string REP_LOT_START {
            get {
                return ResourceManager.GetString("REP_LOT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query finished LOTs only.
        /// </summary>
        public static string REP_QUERY_FINISHED_LOTS {
            get {
                return ResourceManager.GetString("REP_QUERY_FINISHED_LOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query LOTs.
        /// </summary>
        public static string REP_QUERY_LOT {
            get {
                return ResourceManager.GetString("REP_QUERY_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Compensation:.
        /// </summary>
        public static string REST_COMPENSTAION {
            get {
                return ResourceManager.GetString("REST_COMPENSTAION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Dummy:.
        /// </summary>
        public static string REST_DUMMY {
            get {
                return ResourceManager.GetString("REST_DUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string REST_TIME_H {
            get {
                return ResourceManager.GetString("REST_TIME_H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS232 Interface.
        /// </summary>
        public static string RS232_COM {
            get {
                return ResourceManager.GetString("RS232_COM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation.
        /// </summary>
        public static string SIG_COMPENSATION {
            get {
                return ResourceManager.GetString("SIG_COMPENSATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Dummy.
        /// </summary>
        public static string SIG_EDUMMY {
            get {
                return ResourceManager.GetString("SIG_EDUMMY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization.
        /// </summary>
        public static string SIG_INITIALIZATION {
            get {
                return ResourceManager.GetString("SIG_INITIALIZATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Discard.
        /// </summary>
        public static string SIG_LOT_DISCARD {
            get {
                return ResourceManager.GetString("SIG_LOT_DISCARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot End.
        /// </summary>
        public static string SIG_LOT_END {
            get {
                return ResourceManager.GetString("SIG_LOT_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot In Progress.
        /// </summary>
        public static string SIG_LOT_IN_PROGRESS {
            get {
                return ResourceManager.GetString("SIG_LOT_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Pause.
        /// </summary>
        public static string SIG_LOT_PAUSE {
            get {
                return ResourceManager.GetString("SIG_LOT_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Start.
        /// </summary>
        public static string SIG_LOT_START {
            get {
                return ResourceManager.GetString("SIG_LOT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Empty.
        /// </summary>
        public static string SIG_MACHINE_EMPTY {
            get {
                return ResourceManager.GetString("SIG_MACHINE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Ready.
        /// </summary>
        public static string SIG_MACHINE_READY {
            get {
                return ResourceManager.GetString("SIG_MACHINE_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string START_DATE {
            get {
                return ResourceManager.GetString("START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string START_TIME {
            get {
                return ResourceManager.GetString("START_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation Mode.
        /// </summary>
        public static string STATE_COMPENSATION {
            get {
                return ResourceManager.GetString("STATE_COMPENSATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error database.
        /// </summary>
        public static string STATE_DB_ERROR {
            get {
                return ResourceManager.GetString("STATE_DB_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error measurement device.
        /// </summary>
        public static string STATE_DEVICE_ERROR {
            get {
                return ResourceManager.GetString("STATE_DEVICE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error IO Card.
        /// </summary>
        public static string STATE_IO_ERROR {
            get {
                return ResourceManager.GetString("STATE_IO_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate measurement.
        /// </summary>
        public static string STATE_MEASUREMENT_EVALUATE {
            get {
                return ResourceManager.GetString("STATE_MEASUREMENT_EVALUATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement running.
        /// </summary>
        public static string STATE_MEASUREMENT_RUNNING {
            get {
                return ResourceManager.GetString("STATE_MEASUREMENT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready for a new lot.
        /// </summary>
        public static string STATE_READY_FOR_NEW_LOT {
            get {
                return ResourceManager.GetString("STATE_READY_FOR_NEW_LOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to measure.
        /// </summary>
        public static string STATE_READY_TO_MEASURE {
            get {
                return ResourceManager.GetString("STATE_READY_TO_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error RS232 Communication.
        /// </summary>
        public static string STATE_RS232_ERROR {
            get {
                return ResourceManager.GetString("STATE_RS232_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown requested.
        /// </summary>
        public static string STATE_SHUTDOWN {
            get {
                return ResourceManager.GetString("STATE_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait until lot in progress.
        /// </summary>
        public static string STATE_WAIT_UNTIL_LOT_IN_PROGRESS {
            get {
                return ResourceManager.GetString("STATE_WAIT_UNTIL_LOT_IN_PROGRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram 1.
        /// </summary>
        public static string TAB_HIST1 {
            get {
                return ResourceManager.GetString("TAB_HIST1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram 2.
        /// </summary>
        public static string TAB_HIST2 {
            get {
                return ResourceManager.GetString("TAB_HIST2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability.
        /// </summary>
        public static string TAB_PROBABILITY {
            get {
                return ResourceManager.GetString("TAB_PROBABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TAB_STATUS {
            get {
                return ResourceManager.GetString("TAB_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test plan.
        /// </summary>
        public static string TEST_PLAN {
            get {
                return ResourceManager.GetString("TEST_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Report.
        /// </summary>
        public static string TITLE_PRINT_REPORT {
            get {
                return ResourceManager.GetString("TITLE_PRINT_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string TOTAL {
            get {
                return ResourceManager.GetString("TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSMS Status.
        /// </summary>
        public static string TSMS_STATUS {
            get {
                return ResourceManager.GetString("TSMS_STATUS", resourceCulture);
            }
        }
    }
}
